# Generated by Django 2.1.7 on 2019-04-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='分类名')),
            ],
            options={
                'db_table': '分类名',
                'ordering': ['id'],
            },
        ),
    ]
